// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Movies      []*Movie `json:"movies"`
}

type Movie struct {
	ID          string      `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	ReleaseDate string      `json:"releaseDate"`
	Categories  []*Category `json:"categories"`
}

type Mutation struct {
}

type NewCategory struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewMovie struct {
	Title       string   `json:"title"`
	Description string   `json:"description"`
	ReleaseDate string   `json:"releaseDate"`
	CategoryID  []string `json:"categoryId"`
}

type Query struct {
}
